services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ecommerce
      DB_USERNAME: ecommerce
      DB_PASSWORD: secret
    volumes:
      - .:/var/www/html
    ports:
      - "9000:80"
    depends_on:
      - db

volumes:
  pgdata: